import re 
textfile1 = open("Tareasregex/archivo1.txt", "r")
texto1 = textfile1.read()
textfile1.close()
textfile2 = open("Tareasregex/archivo2.txt", "r")
texto2 = textfile2.read()
textfile2.close()
textfile3 = open("Tareasregex/archivo3.txt", "r")
texto3 = textfile3.read()
textfile3.close()
busqueda1 = re.findall(r"curp [\w]+", texto1), re.findall(r"curp [\w]+", texto2), re.findall(r"curp [\w]+", texto3)
print(busqueda1)
busqueda2 = re.findall(r"telefono [\d]+", texto1), re.findall(r"telefono [\d]+", texto2), re.findall(r"telefono [\d]+", texto3)
print(busqueda2)
busqueda3 = re.findall(r"URL [\S]+", texto1), re.findall(r"URL [\S]+", texto2), re.findall(r"URL [\S]+", texto3)
print(busqueda3)
busqueda4 = re.findall(r"tarjeta [\d]+", texto1), re.findall(r"tarjeta [\d]+", texto2), re.findall(r"tarjeta [\d]+", texto3)
print(busqueda4)
busqueda5 = re.findall(r"contrasena [\S]+", texto1), re.findall(r"contrasena [\S]+", texto2), re.findall(r"contrasena [\S]+", texto3)
print(busqueda5)
remplazo1 = re.sub("tarjeta", "tarjetita", texto1)
print(remplazo1)
remplazo2 = re.sub("tarjeta", "tarjetita", texto2)
print(remplazo2)
remplazo3 = re.sub("tarjeta", "tarjetita", texto3)
print(remplazo3)